"use client";

import { type SlideBlockId } from "@/data/slide-templates";

type Props = {
  blockId: SlideBlockId;
  data: Record<string, unknown>;
};

export function SlideBlockPreview({ blockId, data }: Props) {
  switch (blockId) {
    case "title":
      return (
        <div className="flex flex-col justify-center items-center h-full text-center">
          <div className="w-16 h-0.5 bg-[#7319F2] rounded-full mb-4" />
          <h2 className="text-2xl font-bold text-white mb-2">
            {(data.title as string) || "Engineering Metrics Report"}
          </h2>
          <p className="text-sm text-[#E3D1FC]">
            {(data.subtitle as string) || "Generated by Jellyfish Compass"}
          </p>
          <p className="text-xs text-[#E3D1FC]/60 mt-3">
            {new Date().toISOString().split("T")[0]}
          </p>
        </div>
      );

    case "sprint-kpis": {
      const kpis =
        (data.kpis as { label: string; value: string; color: string }[]) || [];
      return (
        <div className="h-full">
          <p className="text-lg font-bold text-white mb-3">Sprint Health KPIs</p>
          <div className="grid grid-cols-2 gap-2 flex-1">
            {kpis.map((kpi) => {
              const colors: Record<string, string> = {
                blue: "#13E2BF",
                green: "#CFEF09",
                amber: "#F59E0B",
                violet: "#7319F2",
              };
              return (
                <div
                  key={kpi.label}
                  className="bg-[#1a1040] rounded-md p-3"
                  style={{
                    borderTop: `3px solid ${colors[kpi.color] || "#7319F2"}`,
                  }}
                >
                  <p className="text-[9px] uppercase tracking-wider text-[#E3D1FC]/70">
                    {kpi.label}
                  </p>
                  <p
                    className="text-xl font-bold"
                    style={{ color: colors[kpi.color] || "#7319F2" }}
                  >
                    {kpi.value}
                  </p>
                </div>
              );
            })}
          </div>
        </div>
      );
    }

    case "sprint-history":
    case "delivery-status":
    case "team-allocation":
    case "capacity-gaps":
    case "benchmarks": {
      const title = (data.title as string) || blockId.replace("-", " ");
      const headers = (data.headers as string[]) || [];
      const rows = (data.rows as string[][]) || [];
      return (
        <div className="h-full overflow-auto">
          <p className="text-lg font-bold text-white mb-3">{title}</p>
          <table className="w-full text-[9px]">
            <thead>
              <tr>
                {headers.map((h) => (
                  <th
                    key={h}
                    className="text-left py-1 px-2 bg-[#7319F2] text-white uppercase tracking-wider font-bold"
                  >
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {rows.slice(0, 6).map((row, i) => (
                <tr
                  key={i}
                  className={i % 2 === 0 ? "bg-[#0D062B]" : "bg-[#1a1040]"}
                >
                  {row.map((cell, j) => (
                    <td key={j} className="py-1 px-2 text-white">
                      {cell}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      );
    }

    case "scope-effort":
    case "allocation-fte":
    case "devex-index": {
      const title = (data.title as string) || blockId.replace("-", " ");
      const bars =
        (data.bars as { label: string; value: number; max: number }[]) || [];
      return (
        <div className="h-full">
          <p className="text-lg font-bold text-white mb-3">{title}</p>
          <div className="space-y-2">
            {bars.map((bar) => {
              const pct = Math.min((bar.value / bar.max) * 100, 100);
              return (
                <div key={bar.label}>
                  <div className="flex justify-between text-[9px] mb-0.5">
                    <span className="text-[#E3D1FC]">{bar.label}</span>
                    <span className="text-[#13E2BF] font-bold">{bar.value}</span>
                  </div>
                  <div className="h-2 bg-[#1a1040] rounded-full overflow-hidden">
                    <div
                      className="h-full bg-gradient-to-r from-[#13E2BF] to-[#7319F2] rounded-full"
                      style={{ width: `${pct}%` }}
                    />
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      );
    }

    case "unlinked-prs": {
      const number = (data.number as string) || "0";
      const subtitle = (data.subtitle as string) || "";
      return (
        <div className="h-full flex flex-col items-center justify-center text-center">
          <p className="text-lg font-bold text-white mb-2">
            Unlinked Pull Requests
          </p>
          <p className="text-5xl font-extrabold text-[#FF502A]">{number}</p>
          <p className="text-xs text-[#E3D1FC]/70 mt-2">{subtitle}</p>
        </div>
      );
    }

    case "dora-metrics":
    case "custom-text": {
      const title = (data.title as string) || "";
      const body = (data.body as string) || "";
      return (
        <div className="h-full">
          <p className="text-lg font-bold text-white mb-3">{title}</p>
          <p className="text-xs text-[#E3D1FC] leading-relaxed whitespace-pre-wrap">
            {body}
          </p>
        </div>
      );
    }

    default:
      return <div className="text-white text-sm">Unknown slide type</div>;
  }
}
