"use client";

import { useState } from "react";
import { ChevronLeft } from "lucide-react";
import { TemplatePicker } from "@/components/metrics/template-picker";
import { SlideList } from "@/components/metrics/slide-list";
import { SlidePreview } from "@/components/metrics/slide-preview";
import { SlideBlockPreview } from "@/components/metrics/slide-blocks";
import { DataSourceToggle } from "@/components/metrics/data-source-toggle";
import { ExportButton } from "@/components/metrics/export-button";
import { templates, type SlideBlockId } from "@/data/slide-templates";
import {
  mockSprintKpis,
  mockSprints,
  mockDeliverables,
  mockScopeEffort,
  mockInvestmentAllocation,
  mockTeamAllocations,
  mockDevExScores,
  mockUnlinkedPrs,
  mockCapacityPlan,
  mockTeamBenchmarks,
} from "@/data/mock-data";
import { doraMetrics } from "@/data/dora-metrics";
import { jellyfishDark, jellyfishLight } from "@/lib/export-pptx-themes";
import type { SlideData } from "@/lib/export-pptx";

export default function MetricsPage() {
  const [templateId, setTemplateId] = useState<string | null>(null);
  const [activeSlides, setActiveSlides] = useState<SlideBlockId[]>(["title"]);
  const [selectedIndex, setSelectedIndex] = useState(0);
  const [dataSource, setDataSource] = useState<"mock" | "api" | "mcp">("mock");
  const [token, setToken] = useState("");
  const [mcpUrl, setMcpUrl] = useState("http://localhost:3100");
  const [exporting, setExporting] = useState(false);
  const [titleText, setTitleText] = useState("Engineering Metrics Report");
  const [subtitleText, setSubtitleText] = useState("Generated by Jellyfish Compass");
  const [panelCollapsed, setPanelCollapsed] = useState(false);
  const [templatePickerOpen, setTemplatePickerOpen] = useState(true);

  // Suppress unused-variable lint for titleText/subtitleText setters — used in the title block data mapper
  void setTitleText;
  void setSubtitleText;

  const currentStep: 1 | 2 | 3 = templateId === null ? 1 : activeSlides.length === 0 ? 1 : 2;

  function handleTemplateSelect(id: string) {
    const tmpl = templates.find((t) => t.id === id);
    if (tmpl) {
      setTemplateId(id);
      setActiveSlides([...tmpl.slides]);
      setSelectedIndex(0);
      setTemplatePickerOpen(false);
    }
  }

  function getMockDataForBlock(blockId: SlideBlockId): Record<string, unknown> {
    switch (blockId) {
      case "title":
        return { title: titleText, subtitle: subtitleText };
      case "sprint-kpis":
        return {
          kpis: [
            { label: "Avg Velocity", value: mockSprintKpis.avgVelocity.value, color: "blue" },
            { label: "Completion Rate", value: mockSprintKpis.completionRate.value, color: "green" },
            { label: "Carry-Over", value: mockSprintKpis.carryOver.value, color: "amber" },
            { label: "Sprint Cadence", value: mockSprintKpis.sprintCadence.value, color: "violet" },
          ],
        };
      case "sprint-history":
        return {
          title: "Sprint History",
          headers: ["Sprint", "Committed", "Completed", "Carry-Over", "Velocity"],
          rows: mockSprints.map((s) => [
            s.name,
            String(s.committed),
            String(s.completed),
            String(s.carryOver),
            String(s.velocity),
          ]),
        };
      case "delivery-status":
        return {
          title: "Delivery Status",
          headers: ["Deliverable", "Category", "Issues", "Complete", "Status"],
          rows: mockDeliverables.map((d) => [
            d.name,
            d.category,
            String(d.issues),
            `${d.percentComplete}%`,
            d.status,
          ]),
        };
      case "scope-effort":
        return {
          title: "Scope & Effort Trend",
          bars: mockScopeEffort.map((w) => ({ label: w.week, value: w.scope, max: 70 })),
        };
      case "allocation-fte":
        return {
          title: "Investment Allocation (FTE)",
          bars: mockInvestmentAllocation.map((a) => ({ label: a.label, value: a.value, max: a.max })),
        };
      case "team-allocation":
        return {
          title: "Team Allocation",
          headers: ["Team", "Total FTE", "Features %", "KTLO %", "Tech Debt %"],
          rows: mockTeamAllocations.map((t) => [
            t.team,
            String(t.totalFte),
            `${t.features}%`,
            `${t.ktlo}%`,
            `${t.techDebt}%`,
          ]),
        };
      case "devex-index":
        return {
          title: "DevEx Index by Team",
          bars: mockDevExScores.map((d) => ({ label: d.team, value: d.score, max: 100 })),
        };
      case "unlinked-prs":
        return {
          title: "Unlinked Pull Requests",
          number: String(mockUnlinkedPrs.total),
          subtitle: "pull requests merged without a linked ticket",
          color: "FF502A",
          breakdown: mockUnlinkedPrs.byTeam.map((t) => ({ label: t.team, value: t.count })),
        };
      case "capacity-gaps":
        return {
          title: "Capacity Gaps",
          headers: ["Team", "Available FTE", "Planned FTE", "Gap", "Status"],
          rows: mockCapacityPlan.map((c) => [
            c.team,
            String(c.availableFte),
            String(c.plannedFte),
            String(c.gap),
            c.status,
          ]),
        };
      case "benchmarks":
        return {
          title: "Team Benchmarks",
          headers: ["Team", "Velocity", "Cycle Time", "PR Review", "Deploys/wk", "DevEx"],
          rows: mockTeamBenchmarks.map((t) => [
            t.team,
            String(t.velocity),
            `${t.cycleTimeDays}d`,
            `${t.prReviewHours}h`,
            String(t.deploymentsPerWeek),
            String(t.devexScore),
          ]),
        };
      case "dora-metrics":
        return {
          title: "DORA Metrics",
          body: doraMetrics.map((m) => `${m.name}: ${m.desc}`).join("\n\n"),
        };
      case "custom-text":
        return { title: "Custom Slide", body: "Add your content here." };
      default:
        return {};
    }
  }

  async function handleExport(exportTheme: "dark" | "light") {
    setExporting(true);
    try {
      const theme = exportTheme === "dark" ? jellyfishDark : jellyfishLight;
      const slideData: SlideData[] = activeSlides.map((blockId) => {
        const data = getMockDataForBlock(blockId);
        if (blockId === "sprint-kpis") {
          const kpis = data.kpis as { label: string; value: string; color: string }[];
          return {
            blockId,
            data: kpis.map((k, i) => ({
              label: k.label,
              value: k.value,
              unit: [
                mockSprintKpis.avgVelocity.unit,
                mockSprintKpis.completionRate.unit,
                mockSprintKpis.carryOver.unit,
                mockSprintKpis.sprintCadence.unit,
              ][i],
              trend: [
                mockSprintKpis.avgVelocity.trend,
                mockSprintKpis.completionRate.trend,
                mockSprintKpis.carryOver.trend,
                mockSprintKpis.sprintCadence.trend,
              ][i],
              color: k.color,
            })),
          };
        }
        return { blockId, data };
      });

      // Dynamic import to avoid bundling node:https at build time
      const { generateDeck } = await import("@/lib/export-pptx");
      const pptx = await generateDeck(slideData, theme, {
        title: titleText,
        subtitle: subtitleText,
      });
      const date = new Date().toISOString().split("T")[0];
      await pptx.writeFile({ fileName: `jellyfish-metrics-${date}.pptx` });
    } finally {
      setExporting(false);
    }
  }

  function handleToggle(blockId: SlideBlockId) {
    if (activeSlides.includes(blockId)) {
      setActiveSlides((prev) => prev.filter((id) => id !== blockId));
      if (selectedIndex >= activeSlides.length - 1) {
        setSelectedIndex(Math.max(0, activeSlides.length - 2));
      }
    } else {
      setActiveSlides((prev) => [...prev, blockId]);
    }
  }

  const currentBlockId = activeSlides[selectedIndex];
  const currentData = currentBlockId ? getMockDataForBlock(currentBlockId) : {};

  return (
    <div className="max-w-[1440px] mx-auto flex flex-col h-screen overflow-hidden">
      {/* ── Toolbar ── */}
      <div className="sticky top-0 z-10 flex items-center h-14 px-4 sm:px-7 gap-4 bg-bg/80 backdrop-blur-xl border-b border-border/50 shrink-0">
        <span className="text-lg font-bold">Deck Builder</span>
        <div className="ml-auto flex items-center gap-3">
          <DataSourceToggle
            source={dataSource}
            token={token}
            mcpUrl={mcpUrl}
            onSourceChange={setDataSource}
            onTokenChange={setToken}
            onMcpUrlChange={setMcpUrl}
          />
          <ExportButton
            onExport={handleExport}
            loading={exporting}
            slideCount={activeSlides.length}
          />
        </div>
      </div>

      {/* ── Step indicator ── */}
      <div className="flex items-center gap-2 px-4 sm:px-7 py-3 text-xs shrink-0 border-b border-border/30">
        {([
          { n: 1, label: "Pick Template" },
          { n: 2, label: "Customize Slides" },
          { n: 3, label: "Export" },
        ] as const).map(({ n, label }, i) => (
          <div key={label} className="flex items-center gap-1.5">
            <div className={[
              "flex items-center gap-1.5 font-medium transition-colors",
              currentStep === n ? "text-blue" : currentStep > n ? "text-text-dim" : "text-text-ghost",
            ].join(" ")}>
              <span className={[
                "w-5 h-5 rounded-full flex items-center justify-center text-[10px] font-bold border",
                currentStep === n ? "bg-blue-interactive text-white border-blue-interactive" : currentStep > n ? "bg-surface-raised border-border text-text-dim" : "border-border text-text-ghost",
              ].join(" ")}>{n}</span>
              {label}
            </div>
            {i < 2 && <span className="text-text-ghost/40 mx-1">→</span>}
          </div>
        ))}
      </div>

      {/* ── Main layout ── */}
      <div className="flex flex-1 overflow-hidden gap-4 px-4 sm:px-7 py-4">
        {/* Left panel */}
        <div className={[
          "shrink-0 flex flex-col gap-4 overflow-y-auto transition-[width] duration-200",
          panelCollapsed ? "w-0 overflow-hidden" : "w-64",
        ].join(" ")}>
          {/* Template picker — collapsible after selection */}
          {templatePickerOpen ? (
            <TemplatePicker selected={templateId} onSelect={handleTemplateSelect} />
          ) : (
            <div className="flex items-center justify-between gap-2 rounded-xl border border-border bg-surface px-4 py-3 text-xs">
              <span className="font-medium truncate text-text-dim">
                {templates.find((t) => t.id === templateId)?.label ?? "Custom"}
              </span>
              <button
                type="button"
                onClick={() => setTemplatePickerOpen(true)}
                className="shrink-0 text-blue hover:underline font-semibold"
              >
                Change
              </button>
            </div>
          )}
          <SlideList
            activeSlides={activeSlides}
            selectedIndex={selectedIndex}
            onReorder={setActiveSlides}
            onToggle={handleToggle}
            onSelect={setSelectedIndex}
          />
        </div>

        {/* Panel collapse toggle */}
        <button
          type="button"
          onClick={() => setPanelCollapsed((v) => !v)}
          aria-label={panelCollapsed ? "Expand panel" : "Collapse panel"}
          className="self-start mt-2 shrink-0 w-5 h-8 flex items-center justify-center rounded border border-border bg-surface-raised text-text-ghost hover:text-text-dim hover:bg-surface transition-colors"
        >
          <ChevronLeft size={12} className={panelCollapsed ? "rotate-180" : ""} />
        </button>

        {/* Right panel — preview */}
        <div className="flex-1 min-w-0 overflow-auto">
          {activeSlides.length === 0 ? (
            <div className="flex items-center justify-center h-full min-h-[520px] rounded-xl border border-dashed border-border text-text-ghost text-sm">
              Add a slide from the left panel to get started.
            </div>
          ) : (
            <SlidePreview
              activeSlides={activeSlides}
              selectedIndex={selectedIndex}
              onPrev={() => setSelectedIndex((i) => Math.max(0, i - 1))}
              onNext={() => setSelectedIndex((i) => Math.min(activeSlides.length - 1, i + 1))}
            >
              {currentBlockId && <SlideBlockPreview blockId={currentBlockId} data={currentData} />}
            </SlidePreview>
          )}
        </div>
      </div>
    </div>
  );
}
